Change log for November 18, 2018 Vulkan 1.1.93 spec update:
  * Update release number to 93.

Public Issues:

  * Add spec language for ename:VK_INDEX_TYPE_NONE_NV and fix up
    slink:VkAccelerationStructureTypeNV (public issue 848).
  * Add missing suffix in description of slink:VkSubpassDescription2KHR
    parameters (public pull request 851).
  * Fix miscellaneous typos (public pull request 855).
  * Add driver ID for Pastel (public pull request 856).
  * Add missing include directive for slink:VkMemoryWin32HandlePropertiesKHR
    implicit valid usage statements (public pull request 857).

Internal Issues:

  * Restrict the storage classes permitted for SPIR-V atomics to what is
    actually supported, in the <<spirvenv-module-validation, Validation
    Rules within a Module>> section (internal issue 1123).
  * Add a missing Valid Usage statement to slink:VkRenderPassCreateInfo for
    the case pname:stencilLoadOp == ename:VK_LOAD_OP_CLEAR, pname:layout ==
    ename:VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL (internal issue
    1408).
  * Modify optimize-pdf script and Makefile to retain non-optimized original
    PDF on errors (internal issue 1435).
  * Add <<spirvenv-module-validation, SPIR-V validation rules>> stating that
    only the listed code:BuiltIn decorations are permitted, and only when
    relevante features and extensions are enabled (internal issue 1449).
  * Remove some duplicated Valid Usage IDs created via cut & paste error
    (internal issue 1455).
  * Build HTML output for extension reference pages (internal issue 1461).
  ** Improve genRef.py handling of aliases defined inside other refpages.
  ** Emit aliases in pygenerator.py.
  ** Add XML noautovalidity flag for VkRenderPassCreateFlags until there
     are some corresponding FlagBits defined.
  ** Corrected types= attribute on some refpage blocks to 'flags'
  ** Added refpage blocks for some missing types detected by CI tests.
  * Fixed many Valid Usage statement issues in slink:VkRenderPassCreateInfo,
    slink:VkSubpassDescription, slink:VkSubpassDescription2KHR,
    slink:VkSubpassDependency2KHR, flink:vkCmdBeginRenderPass,
    flink:vkCmdBeginRenderPass2KHR, and slink:VkRenderPassBeginInfo
    discovered while adding `VK_KHR_create_renderpass2` to the validation
    layers.

New Extensions:

  * `VK_EXT_scalar_block_layout`
  * `VK_EXT_separate_stencil_usage`

diff --git a/config/optimize-pdf b/config/optimize-pdf
--- a/config/optimize-pdf
+++ b/config/optimize-pdf
@@ -68,6 +68,7 @@ fi
 # -dProcessColorModel=/DeviceGray \
 # -dColorConversionStrategy=/Gray \
 
+ERRFILE=ERRS.optimize
 "$GS" -q -dNOPAUSE -dBATCH -dSAFER -dNOOUTERSAVE \
   -sDEVICE=pdfwrite \
   -dPDFSETTINGS=/prepress \
@@ -79,6 +80,17 @@ fi
   -dDownsampleMonoImages=$DOWNSAMPLE_IMAGES \
   -dMonoImageResolution=$IMAGE_DPI \
   -sOutputFile="$FILE_OPTIMIZED" \
-  "$FILE" $FILE_PDFMARK
+  "$FILE" $FILE_PDFMARK 2> $ERRFILE
 
-exit 0
+status=$?
+if test $status -ne 0 ; then
+    echo "$0: $GS return status = $status, aborting"
+elif grep -q Error $ERRFILE ; then
+    echo "$0: $GS succeeded but found Error in $ERRFILE (follows), aborting"
+    echo '---------- Errors from $GS ----------'
+    grep Error $ERRFILE
+    echo '-------------------------------------'
+    status=1
+fi
+
+exit $status
